// ============================================================
// /.netlify/functions/zip-lookup
// ============================================================
// GET ?zip=90630 -> { zip, city, state }
//
// First-party ZIP→place confirmation for the checkout page: when the
// guest finishes typing the shipping ZIP, the UI echoes "Cypress, CA"
// so a typo'd ZIP gets caught at the keyboard — the cheapest place to
// prevent the zone-mismatch under-collection the webhook otherwise has
// to flag for Lusik after the money moved.
//
// Deliberately NOT a third-party API: no latency/availability risk at
// the money moment, no CSP changes, and guests' ZIPs never leave our
// infrastructure. Dataset: netlify/functions/_data/zip-places.json
// (42.5k US ZIPs incl. territories), generated by
// scripts/gen-zip-places.mjs from the BSD-licensed `zipcodes` npm
// package (© 2007 Dav Glass) — attribution preserved here per license.
//
// Display-only: shipping is still priced by _lib/shipping-zones.mjs
// from the ZIP itself; an unknown ZIP here never blocks checkout.
// Responses are CDN-cached hard (the mapping changes ~never), so
// repeat lookups don't even reach the function.
// ============================================================

import PLACES from "./_data/zip-places.json" with { type: "json" };
import { json } from "./_lib/json.mjs";

const cacheHeaders = (seconds) => ({
  "Cache-Control": `public, max-age=${seconds}`,
  "Netlify-CDN-Cache-Control": `public, durable, max-age=${seconds}, immutable`,
});

export default async (req) => {
  if (req.method !== "GET") {
    return json(405, { error: "Method not allowed" });
  }

  const zip = new URL(req.url).searchParams.get("zip") ?? "";
  if (!/^\d{5}$/.test(zip)) {
    return json(400, { error: "zip must be 5 digits" });
  }

  const place = PLACES[zip];
  if (!place) {
    // Cache misses too (briefly) — typos repeat, and the dataset only
    // changes when the committed JSON is regenerated.
    return json(404, { error: "Unknown ZIP" }, cacheHeaders(3600));
  }

  const [city, state] = place;
  return json(200, { zip, city, state }, cacheHeaders(31536000));
};
