// CMS presets (plan §17).
import type { Preset } from "./types.ts";

export const CMS_PRESETS: Preset[] = [
  {
    id: "builtin-git-cms",
    label: "Built-in CMS (git-based)",
    category: "cms",
    difficulty: "easy",
    blurb: "This builder's own CMS: content lives as files in the project, every publish is a git commit, validation gates protect the site.",
    bestFor: ["editing your own site", "version-controlled content", "no extra account"],
    notBestFor: ["large multi-editor newsrooms"],
    recommendedFor: ["Zero extra services: content is files, history is git, and the build gates stop a bad edit from ever publishing."],
    requiredEnvVars: [],
    optionalEnvVars: ["BUILDER_GITHUB_REPO", "BUILDER_GITHUB_TOKEN"],
    npmPackages: [],
    filesToGenerate: ["docs/setup-builtin-cms.md"],
    setupSteps: [
      "Nothing to install — it's part of the builder.",
      "Hosted editing (optional): set BUILDER_GITHUB_REPO + a fine-grained BUILDER_GITHUB_TOKEN so saves commit to GitHub.",
      "Local/offline editing: no configuration at all (files on disk).",
    ],
    validationChecks: ["content directory present", "save gate runs"],
    warnings: ["The GitHub token must be a fine-grained token scoped to ONE repo, contents-only."],
    docsLinks: [],
    canAutoConfigure: true,
    requiresUserAccount: false,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Free — it ships with the builder.",
    requiresPresets: [],
  },
  {
    id: "headless-cms-info",
    label: "External headless CMS (later)",
    category: "cms",
    difficulty: "advanced",
    blurb: "Hosted content platforms (Sanity, Contentful, Payload…) for teams that outgrow git-based editing. Adapter support is planned, not built.",
    bestFor: ["many simultaneous editors", "content shared across several apps"],
    notBestFor: ["single-owner sites (the built-in CMS is simpler and free)"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: [],
    setupSteps: ["Not yet supported — this card exists so the choice is visible. The built-in CMS is the supported path today."],
    validationChecks: [],
    warnings: ["Monthly costs and per-seat pricing are common in this category."],
    docsLinks: [],
    canAutoConfigure: false,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: true,
    requiresPresets: [],
  },
];
