// Commerce presets (plan §17). The generation patterns here mirror the
// reference Lusik & Sons shop: server-trusted prices, signed webhooks,
// checkout logic the visual editor can never touch.
import type { Preset } from "./types.ts";

export const COMMERCE_PRESETS: Preset[] = [
  {
    id: "stripe-checkout",
    label: "Stripe Checkout",
    category: "commerce",
    difficulty: "easy",
    blurb: "Hosted payment page: your site sends the cart, Stripe handles cards, wallets and receipts on their page.",
    bestFor: ["small shops", "fastest safe path to taking payments", "no card data ever touching your site"],
    notBestFor: ["fully custom on-site payment forms"],
    recommendedFor: ["Card data never touches your code, and the server-trusted price pattern generated here is the one battle-tested by this builder's reference shop."],
    requiredEnvVars: ["STRIPE_SECRET_KEY"],
    optionalEnvVars: ["NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"],
    npmPackages: ["stripe"],
    filesToGenerate: ["server/trusted-products.example.mjs", "server/create-checkout-session.example.mjs", ".env.example", "docs/setup-stripe-checkout.md"],
    setupSteps: [
      "Create an account at stripe.com (test mode works without activation)",
      "Copy the secret key into STRIPE_SECRET_KEY (server-side only)",
      "Fill server/trusted-products with your real products + prices in cents",
      "Run a test-mode checkout with card 4242 4242 4242 4242",
      "Activate the account + swap to live keys when ready",
    ],
    validationChecks: ["secret key format (sk_…)", "every sellable product has a trusted price entry"],
    warnings: [
      "The secret key is exactly that — server env vars only, never in browser code or git.",
      "Stripe charges per-transaction fees (no monthly fee).",
      "Prices must come from the server-side trusted list, never from the browser.",
    ],
    docsLinks: [{ label: "Stripe Checkout docs", url: "https://docs.stripe.com/payments/checkout" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    freeTier: "No monthly fee — per-transaction pricing.",
    requiresPresets: [],
  },
  {
    id: "stripe-products",
    label: "Stripe product/price mode",
    category: "commerce",
    difficulty: "standard",
    blurb: "Manage the catalog as Stripe Products & Prices and reference price IDs, instead of a code-side price list.",
    bestFor: ["catalogs edited in the Stripe dashboard", "subscriptions/recurring prices"],
    notBestFor: ["catalogs that must live in the project files"],
    recommendedFor: [],
    requiredEnvVars: ["STRIPE_SECRET_KEY"],
    optionalEnvVars: [],
    npmPackages: ["stripe"],
    filesToGenerate: ["server/price-ids.example.mjs", ".env.example", "docs/setup-stripe-products.md"],
    setupSteps: [
      "Create Products + Prices in the Stripe dashboard",
      "Copy each price ID (price_…) into server/price-ids",
      "Checkout sessions reference the IDs — amounts stay in Stripe",
    ],
    validationChecks: ["all referenced price IDs exist (test fetch)"],
    warnings: ["Catalog edits then live in Stripe's dashboard, not your project files — pick one source of truth."],
    docsLinks: [{ label: "Products & Prices docs", url: "https://docs.stripe.com/products-prices/how-products-and-prices-work" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    requiresPresets: ["stripe-checkout"],
  },
  {
    id: "stripe-webhooks",
    label: "Stripe webhook-ready mode",
    category: "commerce",
    difficulty: "standard",
    blurb: "Signed webhook endpoint scaffold: order persistence, refund handling and abandoned-cart events, verified and deduplicated.",
    bestFor: ["storing orders in your database", "order-status emails", "refund bookkeeping"],
    notBestFor: ["static sites with no server/database"],
    recommendedFor: ["Without webhooks the shop only knows a payment STARTED; this is how orders reliably land in your database."],
    requiredEnvVars: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    optionalEnvVars: [],
    npmPackages: ["stripe"],
    filesToGenerate: ["server/stripe-webhook.example.mjs", ".env.example", "docs/setup-stripe-webhooks.md"],
    setupSteps: [
      "Deploy the site so the webhook URL exists",
      "Stripe dashboard → Webhooks → Add endpoint (URL from the generated docs)",
      "Subscribe to checkout.session.completed, charge.refunded, checkout.session.expired",
      "Copy the signing secret into STRIPE_WEBHOOK_SECRET",
      "Send a test event from the dashboard and confirm it verifies",
    ],
    validationChecks: ["signature verification on a test event", "all three event types subscribed"],
    warnings: ["Unverified webhook handlers are an attack surface — the generated scaffold verifies signatures and rejects everything else. Keep it that way."],
    docsLinks: [{ label: "Stripe webhooks docs", url: "https://docs.stripe.com/webhooks" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    requiresPresets: ["stripe-checkout"],
  },
];
