// Database presets (plan §17).
import type { Preset } from "./types.ts";

export const DATABASE_PRESETS: Preset[] = [
  {
    id: "none-static",
    label: "No database (static site)",
    category: "database",
    difficulty: "easy",
    blurb: "Content lives in the project's files. Simplest, fastest, cheapest — and the right answer for most brochure sites.",
    bestFor: ["business sites", "portfolios", "landing pages", "CMS-content-only sites"],
    notBestFor: ["customer accounts", "orders stored server-side"],
    recommendedFor: ["No accounts to create, no keys to manage, nothing to break — choose a database later only when a feature truly needs one."],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["docs/setup-no-database.md"],
    setupSteps: ["Nothing to set up — content is files in the project."],
    validationChecks: [],
    warnings: [],
    docsLinks: [],
    canAutoConfigure: true,
    requiresUserAccount: false,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Free — there is nothing to host.",
    requiresPresets: [],
  },
  {
    id: "supabase",
    label: "Supabase (Postgres)",
    category: "database",
    difficulty: "easy",
    blurb: "Hosted Postgres with auth, storage and a friendly dashboard — the most batteries-included open option.",
    bestFor: ["apps with login", "beginners who want a dashboard", "Postgres + auth + storage in one"],
    notBestFor: ["pure static sites"],
    recommendedFor: ["One account covers database, auth and file storage — fewest moving parts for an app."],
    requiredEnvVars: ["DATABASE_URL"],
    optionalEnvVars: ["SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
    npmPackages: ["@supabase/supabase-js"],
    filesToGenerate: ["db/schema.sql", ".env.example", "docs/setup-supabase.md"],
    setupSteps: [
      "Create a free project at supabase.com",
      "Copy the connection string into DATABASE_URL",
      "Run db/schema.sql in the SQL editor",
      "If using auth/storage, copy the project URL + keys",
    ],
    validationChecks: ["DATABASE_URL reachable", "schema applied"],
    warnings: ["The service_role key bypasses row security — server-side only, never in the browser.", "Free projects pause after a week of inactivity."],
    docsLinks: [{ label: "Supabase docs", url: "https://supabase.com/docs" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    freeTier: "Free tier: 500 MB database + auth + storage.",
    requiresPresets: [],
  },
  {
    id: "neon",
    label: "Neon (Postgres)",
    category: "database",
    difficulty: "easy",
    blurb: "Serverless Postgres with branching and scale-to-zero. The database the reference Lusik & Sons shop runs on.",
    bestFor: ["plain Postgres without server care", "serverless/functions hosting"],
    notBestFor: ["needing built-in auth/storage (pair with other services)"],
    recommendedFor: ["Just Postgres, done well — and the combination with Netlify + Stripe is validated by this builder's production reference site."],
    requiredEnvVars: ["DATABASE_URL"],
    optionalEnvVars: [],
    npmPackages: ["@neondatabase/serverless"],
    filesToGenerate: ["db/schema.sql", ".env.example", "docs/setup-neon.md"],
    setupSteps: [
      "Create a free project at neon.tech",
      "Copy the connection string into DATABASE_URL",
      "Apply db/schema.sql (psql or the Neon SQL editor)",
    ],
    validationChecks: ["DATABASE_URL reachable", "schema applied"],
    warnings: ["Scale-to-zero means a brief cold start after idle on the free tier."],
    docsLinks: [{ label: "Neon docs", url: "https://neon.tech/docs" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    freeTier: "Free tier with autosuspend.",
    requiresPresets: [],
  },
  {
    id: "firebase",
    label: "Firebase (Firestore)",
    category: "database",
    difficulty: "standard",
    blurb: "Google's app platform: Firestore document database, auth and storage with realtime sync.",
    bestFor: ["realtime apps", "mobile-leaning projects", "Google-ecosystem teams"],
    notBestFor: ["SQL/relational data models", "easy data export later"],
    recommendedFor: [],
    requiredEnvVars: ["FIREBASE_PROJECT_ID"],
    optionalEnvVars: ["FIREBASE_CLIENT_EMAIL", "FIREBASE_PRIVATE_KEY"],
    npmPackages: ["firebase"],
    filesToGenerate: ["firebase.json", ".env.example", "docs/setup-firebase.md"],
    setupSteps: [
      "Create a project at console.firebase.google.com",
      "Enable Firestore (and Auth/Storage if needed)",
      "Copy the web app config / service-account values into env vars",
    ],
    validationChecks: ["project id set", "client SDK initializes"],
    warnings: ["NoSQL model + Google-specific APIs = the highest lock-in on this list; migrating away later is real work."],
    docsLinks: [{ label: "Firebase docs", url: "https://firebase.google.com/docs" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    freeTier: "Spark plan is free with quota limits.",
    requiresPresets: [],
  },
  {
    id: "turso",
    label: "Turso (SQLite)",
    category: "database",
    difficulty: "standard",
    blurb: "Hosted SQLite (libSQL) replicated to the edge — tiny, fast, great for read-heavy apps.",
    bestFor: ["read-heavy apps", "edge/functions hosting", "SQLite fans"],
    notBestFor: ["heavy concurrent writes", "Postgres-specific features"],
    recommendedFor: [],
    requiredEnvVars: ["TURSO_DATABASE_URL", "TURSO_AUTH_TOKEN"],
    optionalEnvVars: [],
    npmPackages: ["@libsql/client"],
    filesToGenerate: ["db/schema.sql", ".env.example", "docs/setup-turso.md"],
    setupSteps: [
      "Create a database at turso.tech (or via the turso CLI)",
      "Copy the database URL + auth token into env vars",
      "Apply db/schema.sql",
    ],
    validationChecks: ["client connects", "schema applied"],
    warnings: [],
    docsLinks: [{ label: "Turso docs", url: "https://docs.turso.tech" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    freeTier: "Generous free tier for small apps.",
    requiresPresets: [],
  },
  {
    id: "cloudflare-d1",
    label: "Cloudflare D1 (SQLite)",
    category: "database",
    difficulty: "advanced",
    blurb: "SQLite on Cloudflare's platform, queried from Workers/Pages Functions.",
    bestFor: ["projects already hosting on Cloudflare Pages/Workers"],
    notBestFor: ["non-Cloudflare hosting (D1 is only reachable from Workers)"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["wrangler.toml", "db/schema.sql", "docs/setup-d1.md"],
    setupSteps: [
      "wrangler d1 create <name>",
      "Add the binding to wrangler.toml",
      "wrangler d1 execute <name> --file db/schema.sql",
    ],
    validationChecks: ["binding present in wrangler.toml"],
    warnings: ["Tightly coupled to Cloudflare hosting — choose it only with Cloudflare Pages."],
    docsLinks: [{ label: "D1 docs", url: "https://developers.cloudflare.com/d1/" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Free tier within Workers limits.",
    requiresPresets: ["cloudflare-pages"],
  },
  {
    id: "render-postgres",
    label: "Render Postgres",
    category: "database",
    difficulty: "standard",
    blurb: "Managed Postgres living next to your Render services — one dashboard for app + database.",
    bestFor: ["projects hosting on Render"],
    notBestFor: ["non-Render hosting (works, but loses the one-dashboard point)"],
    recommendedFor: [],
    requiredEnvVars: ["DATABASE_URL"],
    optionalEnvVars: [],
    npmPackages: ["pg"],
    filesToGenerate: ["db/schema.sql", ".env.example", "docs/setup-render-postgres.md"],
    setupSteps: ["Render: New → Postgres", "Copy the internal connection string into DATABASE_URL", "Apply db/schema.sql"],
    validationChecks: ["DATABASE_URL reachable", "schema applied"],
    warnings: ["Free Postgres instances expire after 30 days — small paid tier for anything real."],
    docsLinks: [{ label: "Render Postgres docs", url: "https://render.com/docs/postgresql" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    requiresPresets: [],
  },
  {
    id: "railway-postgres",
    label: "Railway Postgres",
    category: "database",
    difficulty: "standard",
    blurb: "One-click Postgres inside a Railway project, wired to your services by reference variables.",
    bestFor: ["projects hosting on Railway"],
    notBestFor: ["strictly-free projects (usage billing)"],
    recommendedFor: [],
    requiredEnvVars: ["DATABASE_URL"],
    optionalEnvVars: [],
    npmPackages: ["pg"],
    filesToGenerate: ["db/schema.sql", ".env.example", "docs/setup-railway-postgres.md"],
    setupSteps: ["Railway: New → Database → Postgres", "Reference the DATABASE_URL variable in your service", "Apply db/schema.sql"],
    validationChecks: ["DATABASE_URL reachable", "schema applied"],
    warnings: ["Usage-based billing applies to the database too."],
    docsLinks: [{ label: "Railway Postgres docs", url: "https://docs.railway.com/guides/postgresql" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    requiresPresets: [],
  },
  {
    id: "do-managed-db",
    label: "DigitalOcean Managed DB",
    category: "database",
    difficulty: "advanced",
    blurb: "Production-grade managed Postgres/MySQL clusters with backups and standby nodes.",
    bestFor: ["bigger production apps on DigitalOcean", "teams wanting backups/failover handled"],
    notBestFor: ["hobby projects (starts ~$15/mo)", "beginners"],
    recommendedFor: [],
    requiredEnvVars: ["DATABASE_URL"],
    optionalEnvVars: ["CA_CERT"],
    npmPackages: ["pg"],
    filesToGenerate: ["db/schema.sql", ".env.example", "docs/setup-do-database.md"],
    setupSteps: ["DigitalOcean: Databases → Create cluster", "Add your app as a trusted source", "Copy the connection string + CA cert", "Apply db/schema.sql"],
    validationChecks: ["TLS connection succeeds", "schema applied"],
    warnings: ["No free tier — paid from the first hour."],
    docsLinks: [{ label: "Managed Databases docs", url: "https://docs.digitalocean.com/products/databases/" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    requiresPresets: [],
  },
];
