// Email presets (plan §17): two PROVIDERS (resend, smtp) and two
// CAPABILITIES (admin notifications, customer receipts) that require a
// provider via requiresPresets — the UI offers capabilities only after
// a provider is chosen.
import type { Preset } from "./types.ts";

export const EMAIL_PRESETS: Preset[] = [
  {
    id: "resend",
    label: "Resend",
    category: "email",
    difficulty: "easy",
    blurb: "Developer-friendly transactional email with a clean API and a workable free tier. What the reference shop uses.",
    bestFor: ["order/notification emails", "beginners", "small senders"],
    notBestFor: ["bulk marketing campaigns"],
    recommendedFor: ["Simplest credible way to send transactional email, validated by this builder's reference shop in production."],
    requiredEnvVars: ["RESEND_API_KEY"],
    optionalEnvVars: ["EMAIL_FROM"],
    npmPackages: ["resend"],
    filesToGenerate: ["server/email.example.mjs", ".env.example", "docs/setup-resend.md"],
    setupSteps: [
      "Create a free account at resend.com",
      "Create an API key → RESEND_API_KEY",
      "Verify your domain (DNS records shown in their dashboard) so mail comes from you, not onboarding@resend.dev",
      "Set EMAIL_FROM to e.g. \"Shop Name <orders@yourdomain.com>\"",
    ],
    validationChecks: ["API key sends a test email", "domain verified (or fallback sender acknowledged)"],
    warnings: ["Without domain verification, mail sends from resend.dev and often lands in spam."],
    docsLinks: [{ label: "Resend docs", url: "https://resend.com/docs" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    freeTier: "Free tier: 100 emails/day, 3,000/month.",
    requiresPresets: [],
  },
  {
    id: "smtp",
    label: "Generic SMTP (advanced)",
    category: "email",
    difficulty: "advanced",
    blurb: "Bring any SMTP server — your host's mail, a workspace account, or a relay service.",
    bestFor: ["existing mail infrastructure", "provider-neutral setups"],
    notBestFor: ["beginners (deliverability tuning is on you)"],
    recommendedFor: [],
    requiredEnvVars: ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS"],
    optionalEnvVars: ["EMAIL_FROM"],
    npmPackages: ["nodemailer"],
    filesToGenerate: ["server/email.example.mjs", ".env.example", "docs/setup-smtp.md"],
    setupSteps: [
      "Get SMTP credentials from your mail provider",
      "Fill the SMTP_* env vars",
      "Send a test email and check it isn't spam-foldered (SPF/DKIM on your domain)",
    ],
    validationChecks: ["SMTP connection + auth succeeds", "test email delivered"],
    warnings: ["Deliverability (SPF/DKIM/DMARC) is your responsibility with raw SMTP."],
    docsLinks: [{ label: "Nodemailer docs", url: "https://nodemailer.com" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: false,
    requiresPresets: [],
  },
  {
    id: "admin-notifications",
    label: "Admin notification emails",
    category: "email",
    difficulty: "easy",
    blurb: "Email the owner when something happens: a new order, a contact-form message, a waitlist signup.",
    bestFor: ["owners who live in their inbox", "order alerts"],
    notBestFor: [],
    recommendedFor: ["A shop owner should never have to poll a dashboard to learn an order arrived."],
    requiredEnvVars: ["ADMIN_NOTIFICATION_EMAIL"],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["server/notify-admin.example.mjs", "docs/setup-admin-notifications.md"],
    setupSteps: ["Set ADMIN_NOTIFICATION_EMAIL to the owner's inbox", "Pick which events notify (orders, contact, waitlist)"],
    validationChecks: ["test notification delivered"],
    warnings: ["Email sending must never block the underlying action — the generated scaffold isolates failures (an email outage can't lose an order)."],
    docsLinks: [],
    canAutoConfigure: true,
    requiresUserAccount: false,
    requiresSecretKey: false,
    informational: false,
    requiresPresets: ["resend", "smtp"], // any ONE provider satisfies this (registry treats it as or-list)
  },
  {
    id: "customer-receipts",
    label: "Customer receipt emails",
    category: "email",
    difficulty: "easy",
    blurb: "A warm on-brand confirmation to the customer after checkout — what to expect, what they bought.",
    bestFor: ["shops", "anything with checkout"],
    notBestFor: ["sites without transactions"],
    recommendedFor: ["Stripe's own receipt is a cold ledger line; this one sounds like your brand."],
    requiredEnvVars: [],
    optionalEnvVars: ["EMAIL_FROM"],
    npmPackages: [],
    filesToGenerate: ["server/customer-receipt.example.mjs", "docs/setup-customer-receipts.md"],
    setupSteps: ["Edit the generated template's copy to sound like you", "Wire it to the order-completed event (webhooks preset)"],
    validationChecks: ["test receipt rendered + delivered"],
    warnings: [],
    docsLinks: [],
    canAutoConfigure: true,
    requiresUserAccount: false,
    requiresSecretKey: false,
    informational: false,
    requiresPresets: ["resend", "smtp"],
  },
];
