// Hosting presets (plan §17). Adding a provider = adding one object.
import type { Preset } from "./types.ts";

export const HOSTING_PRESETS: Preset[] = [
  {
    id: "netlify",
    label: "Netlify",
    category: "hosting",
    difficulty: "easy",
    blurb: "Git-connected hosting with builds, serverless functions, forms and previews. The stack this builder's reference site runs on.",
    bestFor: ["beginners", "git-based publishing", "sites with serverless functions"],
    notBestFor: ["always-on servers / websockets"],
    recommendedFor: ["Deploy previews + git publishing match how this builder saves content, and the reference site runs here in production."],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["netlify.toml", ".env.example", "docs/setup-netlify.md"],
    setupSteps: [
      "Create a free account at netlify.com",
      "Push the exported project to a Git repository",
      "In Netlify: Add new site → Import from Git → pick the repo",
      "Set the environment variables from .env.example in Site configuration",
      "Deploy — every git push publishes automatically",
    ],
    validationChecks: ["netlify.toml present", "build command runs locally", "env vars listed in .env.example"],
    warnings: ["Free tier has monthly build-minute limits; heavy rebuild workflows can hit them."],
    docsLinks: [{ label: "Netlify docs", url: "https://docs.netlify.com" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Free tier covers small sites comfortably.",
    requiresPresets: [],
  },
  {
    id: "vercel",
    label: "Vercel",
    category: "hosting",
    difficulty: "easy",
    blurb: "Hosting from the makers of Next.js — zero-config for Next projects, git-connected, generous previews.",
    bestFor: ["Next.js projects", "beginners", "fast global delivery"],
    notBestFor: ["long-running background jobs"],
    recommendedFor: ["Exports from this builder are Next.js projects, which Vercel hosts with zero configuration."],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["vercel.json", ".env.example", "docs/setup-vercel.md"],
    setupSteps: [
      "Create a free account at vercel.com",
      "Push the exported project to a Git repository",
      "Vercel: Add New → Project → import the repo (Next.js is auto-detected)",
      "Add the environment variables from .env.example",
      "Deploy",
    ],
    validationChecks: ["next build succeeds locally", "env vars listed in .env.example"],
    warnings: ["Commercial usage on the free (Hobby) tier is restricted — shops need the paid tier."],
    docsLinks: [{ label: "Vercel docs", url: "https://vercel.com/docs" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Hobby tier is free for personal/non-commercial projects.",
    requiresPresets: [],
  },
  {
    id: "cloudflare-pages",
    label: "Cloudflare Pages",
    category: "hosting",
    difficulty: "standard",
    blurb: "Static + functions hosting on Cloudflare's edge network. Pairs naturally with D1/R2 if you're already in that ecosystem.",
    bestFor: ["static-leaning sites", "Cloudflare-ecosystem projects"],
    notBestFor: ["full Next.js server features (needs the next-on-pages adapter)"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["wrangler.toml", ".env.example", "docs/setup-cloudflare-pages.md"],
    setupSteps: [
      "Create a free account at cloudflare.com",
      "Pages → Create project → connect the Git repository",
      "Set build command and output per docs/setup-cloudflare-pages.md",
      "Add environment variables",
      "Deploy",
    ],
    validationChecks: ["build output mode compatible (static export or next-on-pages)"],
    warnings: ["Next.js server features need an adapter; the static HTML export is the smoother path here."],
    docsLinks: [{ label: "Cloudflare Pages docs", url: "https://developers.cloudflare.com/pages/" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Very generous free tier (unlimited static requests).",
    requiresPresets: [],
  },
  {
    id: "render",
    label: "Render",
    category: "hosting",
    difficulty: "standard",
    blurb: "Simple cloud for web services, static sites and managed Postgres in one dashboard.",
    bestFor: ["apps wanting a real server", "one-dashboard app + database"],
    notBestFor: ["pure static sites (cheaper elsewhere)"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["render.yaml", ".env.example", "docs/setup-render.md"],
    setupSteps: [
      "Create a free account at render.com",
      "New → Blueprint → connect the repo (render.yaml is detected)",
      "Add environment variables",
      "Deploy",
    ],
    validationChecks: ["render.yaml present", "start command runs locally"],
    warnings: ["Free web services sleep after inactivity — first visit after idle is slow."],
    docsLinks: [{ label: "Render docs", url: "https://render.com/docs" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Free tier available; services sleep when idle.",
    requiresPresets: [],
  },
  {
    id: "railway",
    label: "Railway",
    category: "hosting",
    difficulty: "standard",
    blurb: "Developer-friendly app platform — deploy services and databases from one project canvas.",
    bestFor: ["app projects", "quick server + database setups"],
    notBestFor: ["static-only sites", "strict-free-tier budgets"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: [".env.example", "docs/setup-railway.md"],
    setupSteps: [
      "Create an account at railway.com",
      "New Project → Deploy from GitHub repo",
      "Add environment variables",
      "Deploy",
    ],
    validationChecks: ["start command runs locally"],
    warnings: ["Usage-based pricing — there is a small monthly credit, then it's paid."],
    docsLinks: [{ label: "Railway docs", url: "https://docs.railway.com" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Trial credit, then usage-based billing.",
    requiresPresets: [],
  },
  {
    id: "do-app-platform",
    label: "DigitalOcean App Platform",
    category: "hosting",
    difficulty: "standard",
    blurb: "Managed app hosting on DigitalOcean — good fit if you also want their managed databases or droplets later.",
    bestFor: ["teams already on DigitalOcean", "predictable monthly pricing"],
    notBestFor: ["hobby static sites"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: [".do/app.yaml", ".env.example", "docs/setup-do-app-platform.md"],
    setupSteps: [
      "Create an account at digitalocean.com",
      "Apps → Create App → connect the repo",
      "Review the generated app spec (.do/app.yaml)",
      "Add environment variables",
      "Deploy",
    ],
    validationChecks: ["app spec present", "build command runs locally"],
    warnings: ["Mostly paid from the start (small static-site free allowance only)."],
    docsLinks: [{ label: "App Platform docs", url: "https://docs.digitalocean.com/products/app-platform/" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    freeTier: "Static sites have a small free allowance; apps are paid.",
    requiresPresets: [],
  },
  {
    id: "fly-io",
    label: "Fly.io (advanced)",
    category: "hosting",
    difficulty: "advanced",
    blurb: "Run containers close to users worldwide. Powerful, CLI-driven — best when you're comfortable with Docker.",
    bestFor: ["developers", "global low-latency apps", "containerized servers"],
    notBestFor: ["beginners", "no-CLI workflows"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: ["fly.toml", "Dockerfile", ".env.example", "docs/setup-fly.md"],
    setupSteps: [
      "Install the flyctl CLI and sign up",
      "fly launch (reads the generated fly.toml/Dockerfile)",
      "fly secrets set … for each required env var",
      "fly deploy",
    ],
    validationChecks: ["Dockerfile builds locally"],
    warnings: ["CLI + Docker knowledge expected; billing is usage-based."],
    docsLinks: [{ label: "Fly.io docs", url: "https://fly.io/docs/" }],
    canAutoConfigure: true,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: false,
    requiresPresets: [],
  },
];
