// DNS/security presets (plan §17) — ALL informational. They render
// explainer cards; they generate nothing, install nothing, and never
// touch DNS. The schema enforces emptiness; the copy enforces honesty:
// Cloudflare is an option, never a requirement.
import type { Preset } from "./types.ts";

export const SECURITY_PRESETS: Preset[] = [
  {
    id: "cloudflare-info",
    label: "Cloudflare (optional)",
    category: "security",
    difficulty: "easy",
    blurb: "An optional layer in front of any host: DNS, caching CDN, bot protection and a firewall — free tier covers small sites.",
    bestFor: ["custom domains wanting DDoS/bot protection", "free WAF + caching"],
    notBestFor: ["sites happy with their host's defaults — this is OPTIONAL"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: [],
    setupSteps: [
      "Entirely optional — your site works without it.",
      "If wanted: create a free cloudflare.com account, add your domain, and follow THEIR nameserver instructions.",
      "This builder never changes DNS for you — you stay in control of your domain.",
    ],
    validationChecks: [],
    warnings: ["Moving nameservers affects email and subdomains too — read their checklist before switching."],
    docsLinks: [{ label: "Cloudflare DNS docs", url: "https://developers.cloudflare.com/dns/" }],
    canAutoConfigure: false,
    requiresUserAccount: true,
    requiresSecretKey: false,
    informational: true,
    freeTier: "Free plan covers DNS, CDN and basic WAF.",
    requiresPresets: [],
  },
  {
    id: "turnstile-info",
    label: "Cloudflare Turnstile (optional)",
    category: "security",
    difficulty: "standard",
    blurb: "A privacy-friendly CAPTCHA alternative for forms — stops bot spam without making humans click traffic lights.",
    bestFor: ["contact forms getting spam", "signup forms"],
    notBestFor: ["sites without public forms"],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: [],
    setupSteps: [
      "Optional, and only useful once a form actually attracts spam.",
      "If wanted: Cloudflare dashboard → Turnstile → create a widget, then add the site key to the form per their docs.",
    ],
    validationChecks: [],
    warnings: [],
    docsLinks: [{ label: "Turnstile docs", url: "https://developers.cloudflare.com/turnstile/" }],
    canAutoConfigure: false,
    requiresUserAccount: true,
    requiresSecretKey: true,
    informational: true,
    requiresPresets: [],
  },
  {
    id: "cdn-waf-explainer",
    label: "What are CDN / DNS / WAF?",
    category: "security",
    difficulty: "easy",
    blurb: "A plain-language explainer card: what DNS, a CDN and a web application firewall actually do, and when a small site needs each.",
    bestFor: ["understanding the jargon before choosing anything"],
    notBestFor: [],
    recommendedFor: [],
    requiredEnvVars: [],
    optionalEnvVars: [],
    npmPackages: [],
    filesToGenerate: [],
    setupSteps: [
      "DNS = your domain's phone book (which server answers for yourname.com).",
      "CDN = copies of your site stored near visitors so it loads fast everywhere. Most hosts include one already.",
      "WAF = a filter that blocks malicious traffic before it reaches your site.",
      "Small sites usually need: DNS (always), CDN (your host's is fine), WAF (nice-to-have).",
    ],
    validationChecks: [],
    warnings: [],
    docsLinks: [],
    canAutoConfigure: false,
    requiresUserAccount: false,
    requiresSecretKey: false,
    informational: true,
    requiresPresets: [],
  },
];
