// ============================================================
// Service presets — the project's selection document (Phase 17)
// ============================================================
// builder/data/services.json records which presets this project
// chose. Saving it runs validateSelection (unknown ids, broken
// dependencies, doubled exclusive categories are publish-blocking)
// and exports decorate themselves with the resulting checklist.
// ============================================================

import { z } from "zod";
import { buildSetupChecklist, presetById, stackById } from "./index.ts";

export const servicesSelectionSchema = z
  .object({
    schemaVersion: z.number().int().min(1).default(1),
    /** The stack the choices started from (informational). */
    stack: z.string().nullable().default(null),
    selection: z.array(z.string()).default([]),
  })
  .strict();

export type ServicesSelection = z.infer<typeof servicesSelectionSchema>;
export const SERVICES_PATH = "builder/data/services.json";

/** The pre-deploy checklist as markdown — written into exports. */
export function checklistMarkdown(selection: string[], stackId: string | null = null): string {
  const checklist = buildSetupChecklist(selection);
  const stack = stackId ? stackById(stackId) : null;
  const lines: string[] = [
    "# Setup checklist",
    "",
    stack ? `Stack: **${stack.label}** — ${stack.blurb}` : "Services chosen in the builder:",
    "",
    `Selected: ${selection.map((id) => presetById(id)?.label ?? id).join(" · ") || "none"}`,
    "",
  ];
  if (checklist.accountsNeeded.length) {
    lines.push("## Accounts you need", ...checklist.accountsNeeded.map((a) => `- [ ] ${a}`), "");
  }
  if (checklist.envVars.required.length || checklist.envVars.optional.length) {
    lines.push("## Environment variables");
    lines.push(...checklist.envVars.required.map((v) => `- [ ] \`${v}\` (required)`));
    lines.push(...checklist.envVars.optional.map((v) => `- [ ] \`${v}\` (optional)`));
    lines.push("");
  }
  if (checklist.npmPackages.length) {
    lines.push("## Packages", "```", `npm install ${checklist.npmPackages.join(" ")}`, "```", "");
  }
  if (checklist.secretWarnings.length) {
    lines.push(
      "## ⚠ Secret keys",
      `These services use secret keys — server env vars only, never in browser code or git: ${checklist.secretWarnings.join(", ")}.`,
      ""
    );
  }
  if (checklist.warnings.length) {
    lines.push("## Heads-up", ...checklist.warnings.map((w) => `- **${w.preset}:** ${w.warning}`), "");
  }
  for (const step of checklist.steps) {
    lines.push(`## ${step.preset}`, ...step.steps.map((s, i) => `${i + 1}. ${s}`), "");
  }
  lines.push("---", "*Generated by Baghdo's Workshop. Recommendations are informational — any provider works; nothing here locks you in.*", "");
  return lines.join("\n");
}
