// ============================================================
// Retro Game Room — launch composition + verification (pure)
// ============================================================
// Builds the {bin, args[]} a backend needs from a game entry +
// emulator profile. THE SAFETY LAW: launches are always
// spawn(bin, args, {shell:false}) — values are array elements,
// never a concatenated shell string, so a path like
// "My Games; rm -rf" is just a filename. Composition is pure and
// unit-tested; the API route does the spawning (after the
// explicit confirm step the spec requires).
//
// What we compose for each USER-INSTALLED open-source backend:
//   dosbox-x — a generated .conf (mounts the user's ISO) + mapper
//              lines from the controller bindings (real save-state
//              support).
//   86box    — points at the user's own machine folder (snapshots
//              via the emulator's UI; disk-state otherwise).
//   qemu     — memory + the user's disk image + optional ISO as
//              cdrom (snapshots when the disk is qcow2).
// Nothing here downloads or bundles OSes, BIOSes, or games.
// ============================================================

import type { ControllerProfile, EmulatorProfile, GameEntry } from "./schemas.ts";

export interface LaunchPlan {
  bin: string; // relative to portable/retro/emulators/ unless absolute
  args: string[];
  /** Files we generate before launch (path → content). */
  generated: Array<{ path: string; content: string }>;
  /** Honest description of the save support for this combination. */
  saveTier: EmulatorProfile["saveTier"];
  warnings: string[];
}

export interface MissingPath {
  field: string;
  path: string;
}

/** Which configured paths must exist before launch (checked by the API). */
export function pathsToVerify(game: GameEntry, emu: EmulatorProfile): Array<{ field: string; path: string }> {
  const out: Array<{ field: string; path: string }> = [];
  if (game.isoPath) out.push({ field: "isoPath", path: game.isoPath });
  if (game.exePath) out.push({ field: "exePath", path: game.exePath });
  if (game.installPath) out.push({ field: "installPath", path: game.installPath });
  if (emu.machinePath) out.push({ field: "machinePath", path: emu.machinePath });
  return out;
}

const BIN_BY_BACKEND: Record<EmulatorProfile["backend"], string> = {
  "dosbox-x": "dosbox-x",
  "86box": "86Box",
  qemu: "qemu-system-i386",
};

export function composeLaunch(game: GameEntry, emu: EmulatorProfile, controller?: ControllerProfile): LaunchPlan {
  const warnings: string[] = [];
  const generated: Array<{ path: string; content: string }> = [];
  const bin = BIN_BY_BACKEND[emu.backend];
  let args: string[] = [];

  if (emu.backend === "dosbox-x") {
    const confPath = `retro/save-data/${game.id}.dosbox-x.conf`;
    generated.push({ path: confPath, content: dosboxConf(game, emu, controller) });
    args = ["-conf", confPath, ...emu.extraArgs];
  } else if (emu.backend === "86box") {
    if (!emu.machinePath) warnings.push("86Box needs a machine folder you set up once in its own UI (machinePath)");
    args = ["--vmpath", emu.machinePath ?? "retro/vm-images", ...emu.extraArgs];
    if (controller && controller.bindings.length > 0) {
      warnings.push("Controller mapping inside a 86Box VM is configured in the guest OS — the profile is saved for reference");
    }
  } else {
    // qemu
    args = ["-m", String(emu.ramMB)];
    if (emu.machinePath) args.push("-hda", emu.machinePath);
    else warnings.push("QEMU needs a disk image you created from your own Windows install media (machinePath)");
    if (game.isoPath) args.push("-cdrom", game.isoPath);
    else if (game.useDiscDrive) args.push("-cdrom", game.useDiscDrive);
    args.push(...emu.extraArgs);
    if (emu.saveTier === "snapshots" && emu.machinePath && !emu.machinePath.endsWith(".qcow2")) {
      warnings.push("QEMU snapshots need a .qcow2 disk image — this profile will fall back to disk-state saving");
    }
  }

  return { bin, args, generated, saveTier: emu.saveTier, warnings };
}

// ── DOSBox-X config + mapper generation ─────────────────────
function dosboxConf(game: GameEntry, emu: EmulatorProfile, controller?: ControllerProfile): string {
  const lines = [
    "# Generated by the Workshop's Retro Game Room — safe to edit.",
    "[dosbox]",
    `memsize=${Math.min(emu.ramMB, 64)}`,
    "",
    "[sdl]",
    "autolock=true",
    "",
  ];
  if (controller && controller.bindings.length > 0) {
    lines.push("[sdl] mapperfile is generated alongside this conf:", `# mapper: ${game.id}.mapper.txt`, "");
  }
  lines.push("[autoexec]");
  if (game.isoPath) {
    lines.push(`imgmount d "${game.isoPath.replace(/"/g, "")}" -t iso`);
  } else if (game.useDiscDrive) {
    lines.push(`mount d ${game.useDiscDrive.replace(/[^A-Za-z0-9:/\\]/g, "")} -t cdrom`);
  }
  if (game.installPath) lines.push(`mount c "${game.installPath.replace(/"/g, "")}"`, "c:");
  if (game.exePath) lines.push(`"${game.exePath.replace(/"/g, "")}"`);
  return lines.join("\n") + "\n";
}

/** DOSBox-X mapper lines from brand-neutral bindings (best-effort layer). */
export function dosboxMapperLines(controller: ControllerProfile): string {
  const JOY: Record<string, string> = {
    "a-button": "jbutton 0 0",
    "b-button": "jbutton 0 1",
    "x-button": "jbutton 0 2",
    "y-button": "jbutton 0 3",
    "start-button": "jbutton 0 7",
    "select-button": "jbutton 0 6",
  };
  const out = ["# Generated mapper — Workshop Retro Game Room"];
  for (const b of controller.bindings) {
    const joy = JOY[b.input];
    if (!joy) continue;
    if (b.target.kind === "key") out.push(`key_${b.target.value.toLowerCase()} "${joy}"`);
    if (b.target.kind === "mouse-button") out.push(`mouse_${b.target.value} "${joy}"`);
  }
  return out.join("\n") + "\n";
}
