// ============================================================
// Visual-regression baselines — "nothing can break" evidence
// ============================================================
// One full-page screenshot per key page, per Playwright project
// (desktop + mobile). Reduced motion is forced and animations are
// disabled so the theater/DEPTH effects don't add noise. Backend
// Functions are stubbed the same way the e2e suite stubs them, so the
// pages render their normal, in-stock state without Netlify running.
//
// Cart and checkout are intentionally not here yet: they need a seeded
// bag, and the localStorage shape is owned by SiteProvider. Add them
// when a PR touches those pages (seed via the UI, not by hand-writing
// the storage shape).
//
// ---- THE BASELINES ARE GENERATED BY CI, NOT LOCALLY -------------------
// Read this before running `--update-snapshots`.
//
// A committed pixel baseline belongs to the browser that drew it. CI
// installs the Chromium revision pinned by @playwright/test; a sandbox
// that sets PLAYWRIGHT_CHROMIUM_EXECUTABLE is running a DIFFERENT build.
// The two rasterise text differently, and not only in antialiasing: the
// metrics differ enough to change where paragraphs wrap, which changes
// the full-page height by 16 to 32 pixels. Playwright fails outright on a
// size mismatch, so the whole suite goes red at once.
//
// That is exactly what happened: baselines generated in a sandbox passed
// there and failed 8 of 18 in CI. The fix was to take CI's own renders
// (the *-actual.png files in the `visual-diffs` artifact the job uploads
// on failure), verify each was a correct page, and commit those.
//
// So: refreshing a baseline means letting CI draw it.
//   1. Make the change, push, let the Visual baselines job fail.
//   2. Download the `visual-diffs` artifact from that run.
//   3. LOOK at each *-actual.png — this is the step that makes it a
//      review rather than a rubber stamp — then copy them over the
//      matching tests/visual/__snapshots__/<project>/<name>.png.
//   4. Push again; the job should be green.
//
// Running `--update-snapshots` locally is still useful for seeing WHAT
// moved, but do not commit the result unless your Chromium is the pinned
// one. A green local run proves nothing about CI.
// ============================================================
import { test, expect } from "@playwright/test";

// Elements whose text is a live date. Masked in every capture.
const LIVE_DATES = "[data-live-dates]";

const PAGES = [
  ["home", "/"],
  ["shop", "/shop"],
  ["category-blankets", "/shop/blankets"],
  ["pdp-alphabet-blanket", "/shop/blankets/armenian-alphabet-blanket"],
  ["pdp-full-alphabet-blanket", "/shop/blankets/full-alphabet-crib-blanket"],
  ["pdp-days-of-the-week", "/shop/bibs/days-of-the-week-bib-set"],
  ["pdp-custom-name-bib", "/shop/bibs/baby-bib"],
  ["pdp-hye-em-yes", "/shop/bibs/hy-em-armenian-bib"],
  ["journal-post", "/journal/armenian-alphabet-gift"],
  ["story", "/story"],
];

test.beforeEach(async ({ context, page }) => {
  // Pin the capability ladder to "full" so a baseline never depends on the
  // runner's core count, network or battery (the tier projects in the e2e
  // config exercise the other tiers on purpose).
  await context.addInitScript(() => { try { sessionStorage.setItem("lusik_tier_session_v1", "full"); } catch {} });
  // Pin the 3D stage OFF so it renders its fallback. A live canvas is the
  // one thing on these pages whose pixels depend on the runner's GPU
  // driver rather than on the page, and these baselines are already
  // sensitive enough to the browser build (see the note above). The Loom
  // has its own coverage; this suite is here to catch layout breaking.
  await context.addInitScript(() => { try { sessionStorage.setItem("lusik_loom_session_v1", "low"); } catch {} });
  // NOTE: the lead-time dates are computed during the SERVER render, so a
  // browser-side clock pin cannot freeze them. They are masked at capture
  // time instead (see LIVE_DATES below).
  await page.emulateMedia({ reducedMotion: "reduce" });
  // No Netlify Functions in the test server: answer the public reads
  // with quiet, in-stock defaults so every page renders its normal state.
  await page.route("**/.netlify/functions/**", (route) => {
    const url = route.request().url();
    if (url.includes("/inventory")) return route.fulfill({ status: 200, contentType: "application/json", body: "{}" });
    return route.fulfill({ status: 204, body: "" });
  });
});

// Full-page screenshots scroll the whole document, which wakes every
// lazy-loaded photo mid-capture and makes "two consecutive stable
// screenshots" impossible on the long, photo-heavy pages (the mobile
// /shop grid tripped this first). Walk the page once so every image
// has loaded, return to the top, then capture.
async function settle(page) {
  await page.evaluate(async () => {
    const step = Math.max(400, Math.floor(window.innerHeight * 0.8));
    for (let y = 0; y < document.documentElement.scrollHeight; y += step) {
      window.scrollTo(0, y);
      await new Promise((r) => setTimeout(r, 80));
    }
    window.scrollTo(0, 0);
  });
  // Bounded waits: a lazy image that never enters the viewport again,
  // or a page that keeps polling, must not hang the capture.
  await page.waitForLoadState("networkidle", { timeout: 10_000 }).catch(() => {});
  await page.evaluate(() =>
    Promise.race([
      Promise.all(
        Array.from(document.images)
          .filter((img) => !img.complete)
          .map((img) => new Promise((r) => { img.onload = img.onerror = r; }))
      ),
      new Promise((r) => setTimeout(r, 5_000)),
    ])
  );
  await page.evaluate(() => document.fonts?.ready);
  // The stylesheet must have applied; otherwise a broken server would write
  // unstyled baselines in --update-snapshots mode without anyone noticing.
  await expect.poll(() => page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--bg-page").trim()), { timeout: 10_000 }).not.toBe("");
}

for (const [name, path] of PAGES) {
  test(`baseline: ${name}`, async ({ page }) => {
    await page.goto(path, { waitUntil: "networkidle" });
    await settle(page);
    await expect(page).toHaveScreenshot(`${name}.png`, {
      fullPage: true,
      // Anything printing a live date is painted over: product pages quote
      // concrete ship-by and arrives-by dates that move every single day,
      // and re-baselining nine pages each morning is not a test.
      mask: [page.locator(LIVE_DATES)],
    });
  });
}
