// ============================================================
// gen-sitemap.mjs — regenerate public/sitemap.xml from the data
// ============================================================
// Builds the sitemap from the real route set: the static pages, every
// catalog category + product (/shop/<cat>/<product>), and every journal post.
// Run after gen-journal-posts.mjs (it reads the generated post list).
//   npm run gen:sitemap
//
// Excludes the private/transactional routes (/account /admin /cart /checkout),
// which are marked noindex. Served by both builds from /public.
// ============================================================

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { CATALOG } from "../src/data/catalog.js";
import { JOURNAL_POSTS } from "../src/data/journalPostsData.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "public", "sitemap.xml");
const BASE = "https://lusikandsons.com";
const TODAY = new Date().toISOString().slice(0, 10);

const urls = [];
const add = (path, priority, changefreq, lastmod = TODAY) =>
  urls.push({ loc: BASE + path, lastmod, changefreq, priority });

// Static surfaces
add("/", "1.0", "weekly");
add("/shop", "0.9", "weekly");
add("/journal", "0.7", "weekly");
add("/story", "0.8", "monthly");
add("/workshop", "0.7", "monthly");
add("/faq", "0.7", "monthly");
add("/contact", "0.7", "monthly");
add("/shipping", "0.7", "monthly");
add("/newsletter", "0.5", "monthly");
add("/gallery", "0.6", "monthly");

// Shop hierarchy — every category + product page
for (const category of Object.values(CATALOG)) {
  add(`/shop/${category.slug}`, "0.8", "weekly");
  for (const product of category.products) {
    add(`/shop/${category.slug}/${product.slug}`, "0.9", "weekly");
  }
}

// Journal posts
for (const post of JOURNAL_POSTS) {
  add(`/journal/${post.slug}`, "0.6", "weekly");
}

const body = urls
  .map(
    (u) =>
      `  <url>\n` +
      `    <loc>${u.loc}</loc>\n` +
      `    <lastmod>${u.lastmod}</lastmod>\n` +
      `    <changefreq>${u.changefreq}</changefreq>\n` +
      `    <priority>${u.priority}</priority>\n` +
      `  </url>`,
  )
  .join("\n");

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- @generated by scripts/gen-sitemap.mjs — run \`npm run gen:sitemap\` after adding a post/product. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;

writeFileSync(OUT, xml);
console.log(`gen-sitemap: wrote ${urls.length} URLs → ${OUT}`);
