// ============================================================
// gen-pages.mjs — build-time CMS codegen for editable page content
// ============================================================
// Reads content/pages/*.json (edited via the Content Studio at /studio →
// "Site Content") and writes src/data/pagesData.generated.js as CMS_PAGES.
// src/components/HomeView.jsx reads CMS_PAGES for the sections that have been
// moved to the CMS (currently the FAQ). The storefront stays fully static.
//
// Mirrors gen-products.mjs: a prebuild step (via gen:data), and it THROWS —
// failing the build — on invalid data, so bad CMS content can never silently
// ship.
//
// Scope today: ENGLISH FAQ only. The Shipping section is interactive UI (carrier
// links + tracking form), not pure prose, so it stays in the component. The
// bilingual FAQ/shipping copy in src/i18n/translations.js is unrelated (and was
// already dead — nothing reads it via t()); cleaning it up is a separate chore.
// ============================================================

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PAGES_DIR = join(__dirname, "..", "content", "pages");
const OUT_FILE = join(__dirname, "..", "src", "data", "pagesData.generated.js");

function fail(file, msg) {
  throw new Error(`[gen-pages] ${file}: ${msg}`);
}
function reqStr(file, obj, k, where) {
  if (typeof obj[k] !== "string" || obj[k].trim() === "") fail(file, `${where}"${k}" is required and must be a non-empty string`);
}

// Per-page-type validators (keyed by filename without .json).
const VALIDATORS = {
  faq(file, data) {
    reqStr(file, data, "eyebrow");
    reqStr(file, data, "title");
    if (!Array.isArray(data.items) || data.items.length === 0) fail(file, `"items" must be a non-empty array`);
    data.items.forEach((it, i) => {
      if (!it || typeof it !== "object") fail(file, `items[${i}] must be an object`);
      reqStr(file, it, "q", `items[${i}] `);
      reqStr(file, it, "a", `items[${i}] `);
    });
  },
};

function main() {
  const files = existsSync(PAGES_DIR)
    ? readdirSync(PAGES_DIR).filter((f) => f.endsWith(".json")).sort()
    : [];

  const pages = {};
  for (const file of files) {
    const name = file.replace(/\.json$/, "");
    let data;
    try {
      data = JSON.parse(readFileSync(join(PAGES_DIR, file), "utf8"));
    } catch (e) {
      fail(file, `invalid JSON — ${e.message}`);
    }
    const validate = VALIDATORS[name];
    if (!validate) fail(file, `no validator for page "${name}" — add one in scripts/gen-pages.mjs before shipping this content`);
    validate(file, data);
    pages[name] = data;
  }

  const banner =
    "// ============================================================\n" +
    "// AUTO-GENERATED by scripts/gen-pages.mjs — DO NOT EDIT.\n" +
    "// Source of truth: content/pages/*.json (Content Studio / Decap).\n" +
    "// Regenerate: `npm run gen:pages` (runs automatically prebuild).\n" +
    "// ============================================================\n";

  writeFileSync(OUT_FILE, `${banner}export const CMS_PAGES = ${JSON.stringify(pages, null, 2)};\n`);
  console.log(`gen-pages: wrote ${Object.keys(pages).length} page(s) → src/data/pagesData.generated.js`);
}

main();
