// ============================================================
// gen-journal.mjs — port the journal posts into the Replit app
// ============================================================
// Reads ../src/data/journal-posts/*.md (the SAME files the website
// compiles and ios/scripts/gen-journal-swift.mjs ports to Swift)
// with the SAME parse rules — YAML front-matter + p/h2/blockquote
// body nodes, newest first, stable tie order — and writes
// replit-app/src/data/journalPosts.js.
//
// When posts change on main: copy the .md files onto this branch,
// then re-run:  node replit-app/scripts/gen-journal.mjs
// ============================================================

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const POSTS_DIR = join(__dirname, "..", "..", "src", "data", "journal-posts");
const OUT_FILE = join(__dirname, "..", "src", "data", "journalPosts.js");

function parseFrontmatter(raw) {
  const m = raw.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
  if (!m) return { meta: {}, body: raw };
  const meta = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    let value = kv[2].trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    meta[kv[1]] = value;
  }
  if (meta.readMinutes) meta.readMinutes = Number(meta.readMinutes);
  return { meta, body: m[2] };
}

function bodyToNodes(body) {
  const nodes = [];
  for (const para of body.trim().split(/\n\s*\n/)) {
    const t = para.trim();
    if (!t) continue;
    if (t.startsWith("## ")) nodes.push({ type: "h2", text: t.slice(3).trim() });
    else if (t.startsWith("> ")) nodes.push({ type: "blockquote", text: t.slice(2).trim() });
    else nodes.push({ type: "p", text: t.replace(/\n/g, " ") });
  }
  return nodes;
}

const files = readdirSync(POSTS_DIR).filter((f) => f.endsWith(".md")).sort();
const parsed = files.map((f) => {
  const { meta, body } = parseFrontmatter(readFileSync(join(POSTS_DIR, f), "utf8"));
  return {
    slug: meta.slug ?? "",
    title: meta.title ?? "",
    excerpt: meta.excerpt ?? "",
    publishedAt: meta.publishedAt ?? "",
    readMinutes: meta.readMinutes ?? 3,
    content: bodyToNodes(body),
  };
});
parsed.sort((a, b) => (a.publishedAt > b.publishedAt ? -1 : 1));

const banner =
  "// @generated by replit-app/scripts/gen-journal.mjs from src/data/journal-posts/*.md\n" +
  "// Do NOT edit by hand — edit the .md files and re-run the generator.\n";
writeFileSync(OUT_FILE, banner + "export const JOURNAL_POSTS = " + JSON.stringify(parsed, null, 2) + ";\n");
console.log(`gen-journal: wrote ${parsed.length} posts → ${OUT_FILE}`);
