// @generated by ios/scripts/gen-journal-swift.mjs — do NOT edit by hand.
// Source of truth: src/data/journal-posts/*.md (the same files the website
// compiles into journalPostsData.js). After editing posts, re-run:
//   node ios/scripts/gen-journal-swift.mjs
// Parse rules + ordering match scripts/gen-journal-posts.mjs exactly.

import Foundation

/// The 7 journal posts, newest first — the Swift mirror of the web's
/// JOURNAL_POSTS array.
enum JournalPosts {
    static let all: [JournalPost] = [
        JournalPost(
            slug: "a-name-is-a-promise",
            title: "A Name is a Promise",
            excerpt: "In Armenian tradition, a child is often named after a grandparent. The name carries a memory forward. Embroidering it onto something is a way of making that promise material.",
            publishedAt: "2026-05-17",
            readMinutes: 3,
            content: [
                .p("There's a tradition in Armenian families -- older than anyone alive can remember and still practiced quietly today -- of naming children after their grandparents or great-grandparents. Not always immediately, and not always the obvious match (you might name your son after your wife's father if your own son was named after yours), but the rule of thumb is that a name in the family doesn't get retired. It gets carried forward."),
                .p("The reasoning is partly religious, partly cultural, partly something quieter than either. Armenian Apostolic baptism includes a name. The priest asks \"What name is given to this child?\" before the cross is made. A name chosen with intention -- chosen because someone you loved had it -- turns a baptism into a continuity. The infant isn't just being welcomed into a faith. They're being told, before they can understand the words, that they are connected to someone specific who came before."),
                .p("This is one reason Armenian first names tend toward the deliberate. Anahit, Mariam, Hasmik, Tigran, Vahan, Hovsep. Each name has a meaning and most have a history -- a saint, a king, a grandmother, a great-uncle who survived something. The name carries a small file of who that person was and what they meant. When parents name a baby Levon because of a grandfather named Levon, they are saying: this is not a new person who happens to share a name. This is a continuation."),
                .p("That's what makes embroidering a child's name onto something different from printing it on something. The everyday name bib Lusik machine-embroiders with your child's name will be in the kitchen, on the floor, in the wash, in the diaper bag, on the high chair, every single day. The name is right there on the fabric. The blanket she hand-cross-stitches with the first letter will go in the crib, on the stroller, in the photos, eventually in a drawer for later, eventually maybe into the next child's hands. The name and the letter are physical objects."),
                .p("In a culture that has spent a century carrying names across continents and decades, putting a name on cloth is not just decoration. It is a way of saying: we remembered. We are still here. This name is still being said.")
            ]
        ),
        JournalPost(
            slug: "tatiks-hands",
            title: "Tatik's Hands",
            excerpt: "Every Armenian household had a grandmother who could cross-stitch. The skill used to be like knowing how to make bread -- invisible, unremarkable, everywhere. It isn't anymore.",
            publishedAt: "2026-05-17",
            readMinutes: 4,
            content: [
                .p("Ask any Armenian over forty about the textiles in their childhood home, and you'll get the same answer: the cross-stitched runner on the dresser was made by tatik. The pillowcases were made by tatik. The cloth folded under the coffee tray was made by tatik. The lacework on the curtain edges, the tablecloth that came out for visitors, the small embroidered handkerchief tucked into a drawer \"for someday\" -- all tatik."),
                .p("It wasn't unusual. In an Armenian village in the early twentieth century, cross-stitch was a skill girls learned alongside reading. Not as a hobby, not as art with a capital A -- as something practical, the way you learn to fold a sheet or salt an eggplant. Every household had stitched textiles because every woman in the household could make them. A daughter's hope chest would include things she'd embroidered herself, sometimes for years. The skill traveled with her into a new marriage and into a new home."),
                .p("That isn't the world we live in anymore. The grandmothers who knew the patterns by heart -- the cross-hatch borders, the pomegranate motif, the symmetrical bird-and-tree designs that show up across Armenian textiles from Van to Karabagh -- are mostly gone now, or very old. Their daughters learned a little. Their granddaughters learned almost none. Walk into an Armenian-American home in Glendale in 2026 and you'll find beautiful textiles, but the woman who made them is more likely to be a museum than a person sitting in the kitchen."),
                .p("Lusik learned from her mother and her aunt. She does cross-stitch the slow way, the village way -- on aida cloth, by hand, without a chart projected onto the fabric. The blanket she makes for your child is the same kind of object that, in 1915, women carried out of Anatolia in their hands because they refused to leave it behind. It isn't a craft revival. It's a craft that's still being practiced by someone whose hands remember."),
                .p("The blanket is one of those objects. So is the act of buying it from someone who can still make it.")
            ]
        ),
        JournalPost(
            slug: "the-two-crafts",
            title: "Why the Everyday Name Bib is Machine-Embroidered and the Heritage Pieces Are Hand-Stitched",
            excerpt: "Both are old crafts, chosen for different reasons. Here's what each one is good for — and why the everyday name bib and the heritage cross-stitched pieces are made by different methods on purpose.",
            publishedAt: "2026-05-17",
            readMinutes: 4,
            content: [
                .p("The blanket and the everyday name bib are different products made by different methods, and that's deliberate. People sometimes ask why the everyday bib isn't hand-stitched too. The honest answer is: a bib that goes through the wash three times a week is a thing that gets ruined."),
                .p("A baby bib lives the hardest life of any object in a house. It catches breastmilk, formula, mashed avocado, blueberry yogurt that stains permanently no matter how fast you rinse, the contents of an entire bowl of oatmeal that the baby flipped, and the small lake of drool produced during teething. It goes through the washing machine three or four times a week. If you have one bib, you wash it constantly. If you have several, each one still cycles through every few days. By the end of a year, even a good bib has been through 150 wash cycles. By the end of the toddler stage, more like 400."),
                .p("Machine embroidery is built to survive that. The thread is locked tightly into the fabric by a tensioned needle moving at hundreds of stitches per minute. The letters don't shift, fray, or pull loose. Lusik uses commercial-grade thread and a proper digitized pattern, so the personalization on her bibs holds up through the wash and through the wear. It's a forty-dollar product designed to look the same on day 400 as it did on day one."),
                .p("The blanket is the opposite category. A hand cross-stitched blanket on aida cloth, with the first letter of a child's name set into a frame of cross-stitched borders, is not a daily-use object the same way. It's a crib blanket, a stroller blanket, the blanket in the going-home-from-the-hospital photo. It's washed by hand, dried flat, folded into a drawer between uses. It will outlast the childhood it was made for. Most likely it will be folded into a chest for the next baby, or for a grandchild thirty years from now."),
                .p("That difference in lifespan changes the math. A hand-stitched blanket takes Lusik about thirty to forty hours to complete. That's only worth it because the blanket will be in a family for fifty years. An everyday name bib that took eight hours to hand-stitch would be unrecognizable after the third washing. Machine embroidery on that bib does what cross-stitch does on the blanket: it puts the name where it belongs, in the form that survives."),
                .p("There's a third category, though, and it's worth naming because it's where most of Lusik's heart goes: the heritage bibs. The Days-of-the-Week set, the Hye Em Yes bib, the Mama & Papa's Anushig pair, the Bari Akhorzhak bib and burp cloth — these she cross-stitches by hand, the same as the blanket. They're not the bib you clip on for a bowl of oatmeal and throw in the wash that night. They're the bib for the christening photo, the baby shower, the first Easter at church — kept, not used up, and handed down like the blanket. So the rule isn't \"blankets are hand-stitched, bibs are machined.\" The rule is the one underneath it: the everyday piece gets the method that survives daily life, and the heritage piece gets the hand that makes it worth keeping."),
                .p("Two crafts. The right one for each job. Sometimes that's the machine, and sometimes — for the pieces a family means to keep — it's Lusik's own hands.")
            ]
        ),
        JournalPost(
            slug: "why-glendale",
            title: "Why Glendale",
            excerpt: "The largest Armenian community in the United States lives in a stretch of suburban Los Angeles between the 5 and the 134. Here's how that happened, and why a workshop in Cypress is part of it.",
            publishedAt: "2026-05-17",
            readMinutes: 5,
            content: [
                .p("If you drive down Brand Boulevard in Glendale on a Sunday morning, you'll hear Armenian spoken on the street. Not in pockets, not at one specific church or restaurant -- on the street. There are bakeries with signage in two scripts. There are grocery stores where the produce section labels everything in English and Armenian. There are city council meetings conducted in both languages. Glendale, California is the largest concentration of Armenians anywhere in the United States, and one of the largest outside of Armenia itself."),
                .p("The community got here in three waves. The first arrived after 1915 -- survivors of the Armenian Genocide who eventually made their way through Lebanon, Syria, France, and finally California. They came in small numbers at first, often choosing Fresno because of the agricultural climate, and only later spreading south. The second wave came from Iran in the late 1970s and early 1980s, fleeing the Iranian Revolution. They had money, education, businesses to rebuild, and they concentrated in Los Angeles. The third wave came after 1991, when Armenia became independent of the Soviet Union and economic collapse pushed a generation outward."),
                .p("Why Glendale specifically? Partly the climate -- Mediterranean weather, just like Yerevan. Partly the network effect -- once a few thousand Armenians settled there, more followed, drawn by the schools, the Apostolic and Catholic churches, the cultural organizations like the AGBU, and the simple fact that you could buy lavash and apricots without driving an hour. By the 2000s, Glendale was so visibly Armenian that the public schools offered Armenian as a foreign language credit."),
                .p("Lusik works out of Cypress, in northern Orange County, about forty-five minutes south of Glendale. That's part of the same diaspora geography -- there are smaller Armenian communities in Orange County, Pasadena, La Crescenta, Burbank, and increasingly the Valley. The kids she stitches blankets for are mostly second- or third-generation Armenian-Americans. Their parents, in their thirties and forties, grew up in the United States but want their American-born children to have something in the house that connects them -- a soft, durable, daily object with their first letter on it, in the alphabet their great-great-grandparents read."),
                .p("That's the quiet thing the blanket does. It's a thread back across the diaspora.")
            ]
        ),
        JournalPost(
            slug: "armenian-alphabet-gift",
            title: "The Armenian Alphabet: A 1,600-Year-Old Gift",
            excerpt: "Mesrop Mashtots designed the alphabet in 405 AD. Sixteen centuries later, those same first three letters — Ա Բ Գ — are still the first ones Armenian children learn.",
            publishedAt: "2026-05-14",
            readMinutes: 3,
            content: [
                .p("The Armenian alphabet was created in 405 AD by a monk named Mesrop Mashtots, commissioned by King Vramshapuh and the Catholicos Sahak Parthev. Before that, Armenian was written in Greek, Syriac, or Persian script — but none of those captured the actual sounds of the spoken language. Mashtots designed a 36-letter alphabet that matched every Armenian sound, and that core has survived nearly intact for sixteen centuries."),
                .p("The first three letters — Ա (Ayb), Բ (Ben), Գ (Gim) — are the alphabet's opening. They're the letters Armenian children learn first. The Armenian word for \"alphabet\" itself, Այբուբեն (Aybuben), is built from the names of the first two letters, the way \"alpha-beta\" became \"alphabet\" in Greek."),
                .h2("Why the first three letters matter"),
                .p("To stitch Ա Բ Գ onto a blanket is to give a child the beginning of their language — literally the first three steps into reading it. It's a quiet kind of inheritance: nobody's reading the blanket to the baby yet, but the letters are there, and one day the same child who slept under them will recognize them on a page."),
                .p("Two more letters were added during the Middle Ages: Օ (Oh) and Ֆ (Feh), bringing the total to 38. The original 36 are still what most Armenian primers teach as \"the alphabet,\" and you'll still see the Mashtots-era letters in old monastery inscriptions if you ever travel to Echmiadzin or Geghard."),
                .h2("Or English, if that's the right gift"),
                .p("The English ABC follows the same logic. Some families want their child's first letters in Armenian; others want English; many want both. Lusik stitches whichever the parent picks — she doesn't push one over the other. The blanket should be the language the family speaks at home."),
                .p("For other letters or special requests — a child's specific initial, an unusual combination, or a custom blanket for a name you'd like spelled out — write Lusik at hello@lusikandsons.com.")
            ]
        ),
        JournalPost(
            slug: "why-cross-stitch",
            title: "Why Cross-Stitch, and Not Just Embroidery",
            excerpt: "Most people use the two words interchangeably. They're not the same thing — and the difference is why Lusik's blanket has to be made by hand.",
            publishedAt: "2026-05-07",
            readMinutes: 4,
            content: [
                .p("Cross-stitch and embroidery aren't the same thing, even though most people use the words interchangeably."),
                .p("Embroidery is a broad family of techniques — satin stitch, French knots, chain stitch, machine embroidery — basically any way of decorating fabric with thread. Cross-stitch is one specific technique within that family, but it's old enough and exacting enough to deserve its own name."),
                .h2("What makes a stitch a cross-stitch"),
                .p("Every mark on the fabric is a small X — two diagonal threads crossing at a single point. The whole picture is built out of those Xs, counted one at a time onto a fabric with an even, gridded weave. There's no improvisation in the stitches themselves; the variation comes entirely from which Xs you place and what color thread you use."),
                .p("This is why cross-stitch is sometimes called \"counted embroidery\": you literally count squares of fabric to know where each X goes. The waffle-weave blankets Lusik uses have the count built into the cloth itself — every little square is one stitch."),
                .h2("Why a machine can't really do it"),
                .p("Machine embroidery uses different stitches — satin and fill — optimized for speed and density. The result is closer to a painted-on image: smooth, regular, opaque. Hand cross-stitch produces something different. You can see the individual stitches, you can feel the texture, and (on the back) you can see the path the stitcher took through the cloth."),
                .p("That visibility is part of why cross-stitched gifts get kept. The work is in the work. A grandmother who learned cross-stitch from her grandmother, who learned it from hers, makes something a machine can't approximate at any price."),
                .h2("Why the bib is different"),
                .p("Lusik does the blanket by hand because the blanket is where the count and texture matter. The bib is machine-embroidered because its surface is too small for hand cross-stitch — a name in cross-stitch on a bib would be unreadable. Each piece gets the technique that suits its size.")
            ]
        ),
        JournalPost(
            slug: "pomegranate-in-textiles",
            title: "The Pomegranate in Armenian Textiles",
            excerpt: "There's a reason every Armenian rug, plate, and manuscript seems to have one. The pomegranate is the country's visual shorthand — and it's woven into Lusik's blankets too.",
            publishedAt: "2026-04-29",
            readMinutes: 3,
            content: [
                .p("If you've ever been in an Armenian home, you've probably seen a pomegranate somewhere. On a tablecloth, woven into a rug, painted on a plate, illuminated in an old manuscript. The pomegranate is, more than any other symbol, the visual shorthand for Armenia."),
                .p("There's a reason."),
                .h2("Abundance, marriage, family"),
                .p("The fruit grows wild in the Armenian highlands — pomegranate trees are an everyday sight. But the symbolism runs deeper. In Armenian folklore, the pomegranate represents abundance, fertility, marriage, and family. The seeds inside (which can number in the hundreds) stand for many children, much grace, a full life. At Armenian weddings, the bride traditionally throws a pomegranate against a wall: the seeds that scatter are blessings on the marriage."),
                .h2("In textiles specifically"),
                .p("In Armenian rug and textile work, the pomegranate appears in stylized, geometric form. The fruit's distinctive crown becomes a small angular tuft at the top; the body is a circle or stylized teardrop. Look at any Armenian rug from the last few centuries and you'll find pomegranates worked into the border or repeated through the field."),
                .h2("On the blanket"),
                .p("Lusik chose her blankets specifically for their pomegranate-pattern waffle weave. The pattern is woven into the fabric itself, not stitched on top — small, repeating, embossed across the entire surface. When she cross-stitches the alphabet over it, the pomegranates stay visible underneath, framing each letter the way they'd frame a child's name on an Armenian heirloom from a century ago."),
                .p("The blanket carries the symbol whether you notice it or not. A child can grow up underneath pomegranates without ever knowing why, and still inherit something Armenian.")
            ]
        )
    ]
}
